### ISSUE TITLE
[UI/UX] bouton "s'inscrire" caché à la création du compte

### ISSUE THREAD

**Issue by coldPen** [aouf/aouf-lowtech#1]
**Décrivez le problème**
Le clavier apparait dès l'ouverture de la page et cache le bouton "S'inscrire". Lors du test, la participante a tapé son login et mdp alors qu'elle n'avait jamais créé de compte.

**Reproduire**
Exemple d'étapes pour reproduire le problème:
1. Allez à https://beta.aouf.fr/, sans avoir été inscrit au préalable
2. L'utilisateur peut croire qu'il s'agit d'un formulaire d'inscription : il remplit les deux champs "Identifiant" et "Mot de passe"
3. Bouton "S'inscrire", pour accéder à un autre formulaire, est caché par le clavier

**Comportement prévisible**
Compte tenu d'une faible hauteur d'écran disponible, l'utilisateur devrait connaître immédiatement la nature du formulaire affiché. Aussi, l'autofocus sur le formulaire de connexion cache la moitié de l'écran dès l'ouverture, alors que l'utilisateur ne souhaite pas forcément se connecter mais peut-être s'inscrire.

**Suggérez une correction**
- Retirer l'autofocus
- Mettre le bouton "s'inscrire" au-dessus du formulaire de connexion

**Comment by gcolpart** [comment]
J'ai implémenté la suggestion d'ajouter un bouton au dessus du formulaire (c'est en prod).

**Comment by Nanaui** [comment]
//URGENT//
Il serait préférable d'enlever l'autofocus et du coup d'enlever aussi le bouton au dessus du formulaire, car pour l'instant nous n'avons que des "1ère inscription" (d'où les feedbacks) mais à l'utilisation dans la durée il vaut mieux avoir l'inscription en second plan.
